In [1]:
import numpy as np
import chainer.functions as F
from chainer import optimizers
from chainer import Variable 


In [2]:
model = F.Linear(4,4)
optimizer = optimizers.SGD()
optimizer.setup(model)


In [3]:
x = Variable(np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]], dtype=np.float32))
t = Variable(np.array([[2,4,6,8], [10,12,14,16], [18,20,22,24]], dtype=np.float32))

In [4]:
for i in range(500):
    optimizer.zero_grads()
    y = model(x)
    loss = F.mean_squared_error(y, t)
    print(loss.data)
    loss.backward()
    optimizer.update()


744.1448364257812
5.612366199493408
0.5888268947601318
0.5482084155082703
0.5415159463882446
0.5351296663284302
0.5288203954696655
0.5225850939750671
0.5164239406585693
0.5103351473808289
0.5043181777000427
0.49837175011634827
0.4924958050251007
0.4866892397403717
0.48095083236694336
0.4752802848815918
0.46967604756355286
0.46413910388946533
0.45866653323173523
0.4532582759857178
0.4479144513607025
0.44263362884521484
0.4374145567417145
0.4322575330734253
0.4271611273288727
0.42212414741516113
0.4171473979949951
0.4122292995452881
0.40736910700798035
0.40256571769714355
0.3978191912174225
0.39312875270843506
0.38849398493766785
0.3839132785797119
0.37938666343688965
0.3749140202999115
0.3704932928085327
0.36612510681152344
0.3618084192276001
0.35754266381263733
0.3533268868923187
0.34916093945503235
0.34504440426826477
0.3409762680530548
0.33695587515830994
0.3329830467700958
0.3290570080280304
0.3251773416996002
0.3213435113430023
0.31755444407463074
0.31381046772003174
0.310110181570

In [5]:
print(y.data)

[[  2.0867734    4.00673532   5.973032     7.92142344]
 [ 10.02474308  12.0019207   13.99231148  15.97759438]
 [ 17.96271324  19.99710464  22.01158905  24.03376389]]
